import 'package:flutter/foundation.dart';

import '../models/post_model.dart';
import '../services/database_service.dart';

class PostProvider extends ChangeNotifier {
  final DatabaseService _databaseService = DatabaseService();

  List<PostModel> _posts = [];
  bool _isLoading = false;
  bool _isLoadingMore = false;
  String? _error;
  bool _hasMore = true;

  List<PostModel> get posts => _posts;
  bool get isLoading => _isLoading;
  bool get isLoadingMore => _isLoadingMore;
  String? get error => _error;
  bool get hasMore => _hasMore;

  // Fetch posts (initial load)
  Future<void> fetchPosts({bool refresh = false}) async {
    if (refresh) {
      _posts = [];
      _hasMore = true;
    }

    _setLoading(true);
    _error = null;

    try {
      final fetchedPosts = await _databaseService.getPosts(limit: 20);

      if (fetchedPosts.isEmpty) {
        _hasMore = false;
      } else {
        _posts = fetchedPosts;
        _hasMore = fetchedPosts.length >= 20;
      }

      notifyListeners();
    } catch (e) {
      _error = 'Failed to load posts: $e';
      debugPrint('Error fetching posts: $e');
    } finally {
      _setLoading(false);
    }
  }

  // Create a new post
  Future<bool> createPost({
    required String userId,
    required String content,
    List<String> imageUrls = const [],
    String? videoUrl,
    bool isAIGenerated = false,
  }) async {
    _error = null;

    try {
      // Create post model (ID will be generated by Firestore)
      final post = PostModel.create(
        id: '', // Firestore will assign the ID
        userId: userId,
        content: content,
        type: imageUrls.isNotEmpty
            ? PostType.image
            : (videoUrl != null ? PostType.video : PostType.text),
        imageUrls: imageUrls,
        videoUrl: videoUrl,
        isAIGenerated: isAIGenerated,
      );

      final postId = await _databaseService.createPost(post);

      if (postId != null) {
        // Add the new post to the beginning of the list
        final newPost = post.copyWith(id: postId);
        _posts.insert(0, newPost);
        notifyListeners();
        return true;
      } else {
        _error = 'Failed to create post';
        return false;
      }
    } catch (e) {
      _error = 'Failed to create post: $e';
      debugPrint('Error creating post: $e');
      return false;
    }
  }

  // Delete a post
  Future<bool> deletePost(String postId, String userId) async {
    _error = null;

    try {
      final success = await _databaseService.deletePost(postId, userId);

      if (success) {
        _posts.removeWhere((post) => post.id == postId);
        notifyListeners();
        return true;
      } else {
        _error = 'Failed to delete post';
        return false;
      }
    } catch (e) {
      _error = 'Failed to delete post: $e';
      debugPrint('Error deleting post: $e');
      return false;
    }
  }

  // Like a post
  Future<bool> likePost(String postId, String userId) async {
    try {
      final success = await _databaseService.likePost(postId, userId);

      if (success) {
        // Update local post
        final index = _posts.indexWhere((post) => post.id == postId);
        if (index != -1) {
          _posts[index] = _posts[index].copyWith(
            likesCount: _posts[index].likesCount + 1,
          );
          notifyListeners();
        }
        return true;
      }
      return false;
    } catch (e) {
      debugPrint('Error liking post: $e');
      return false;
    }
  }

  // Unlike a post
  Future<bool> unlikePost(String postId, String userId) async {
    try {
      final success = await _databaseService.unlikePost(postId, userId);

      if (success) {
        // Update local post
        final index = _posts.indexWhere((post) => post.id == postId);
        if (index != -1) {
          _posts[index] = _posts[index].copyWith(
            likesCount: _posts[index].likesCount - 1,
          );
          notifyListeners();
        }
        return true;
      }
      return false;
    } catch (e) {
      debugPrint('Error unliking post: $e');
      return false;
    }
  }

  // Check if user has liked a post
  Future<bool> hasUserLikedPost(String postId, String userId) async {
    // This would need to be implemented in DatabaseService
    // For now, return false
    return false;
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }

  void clearError() {
    _error = null;
    notifyListeners();
  }

  void clear() {
    _posts = [];
    _isLoading = false;
    _isLoadingMore = false;
    _error = null;
    _hasMore = true;
    notifyListeners();
  }
}
